export const robots=[
    {id:1,
    name:'Erwin Smith',
    regement:'scout',
    rank:'Commander'},
    {id:2,
    name:'Mike Zachariah',
    regement:'scout',
    rank: 'Section commander',
    },
    {id:3,
    name:'Levi Ackermann',
    regement:'scout',
    rank:'Captain',
    },
    {id:4,
    name:'Pixis',
    regement:'Garrison',
    rank:'Commander',
    },
    {id:5,
    name:'Nile Dot',
    regement:'Military Police',
    rank:'Commander',
    },
    {id:6,
    name:'Hange Zoe',
    regement:'Scout',
    rank:'Section Commander',
    },
    {id:7,
    name:'Reiner braun',
    regement:'Scout',
    rank:'Recruit',
    },
    {id:8,
    name:'Eren Jeager',
    regement:'Scout',
    rank:'Recruit',
    },
    {id:9,
    name:'Forman',
    regement:'Garrison Regement',
    rank:'Captain',
    },
    {id:10,
    name:'John Kristian',
    regement:'Scout',
    rank:'Recruit',
    },

]